### ISSUE TITLE
Joplin 2.6.9: Toogle sort order field not styled

### ISSUE THREAD

**Issue by jabums** [andrejilderda/joplin-macos-native-theme#44]
Hi Andre,
I recently updated my Joplin installation to version 2.6.9. - unfortunately some UI elements seem to have been added or changed. In the second column top there now appears an icon that is not well matched with the rest of the style.
May I kindly ask for you to adopt this element?
Thanks!

<img width="538" alt="Bildschirmfoto 2021-12-18 um 11 18 45" src="https://user-images.githubusercontent.com/96083516/146637689-21a4ce86-92ef-4952-aba1-afeb514f341b.png">

**Comment by andrejilderda** [comment]
Hi @jabums, yes, this definitely needs fixing, but imo within Joplin itself. I find the whole split button weird and the icons confusing. Since this is just a theme my options are limited to replacing the icons, but that doesn't really fix the UX-design problem imo. Also, there is not a good [macOS UI pattern](https://developer.apple.com/design/human-interface-guidelines/macos/overview/visual-index/) for this, which is why I'm hesitant to pick this up. Any ideas?

**Comment by andrejilderda** [comment]
I finally made some time to work on this:
[Uploading 2022-03-06 16.48.48.gif…]()

The update should be available in around 20 min.
