### ISSUE TITLE
Changing Fonts

### ISSUE THREAD

**Issue by IkelAtomig** [andrejilderda/joplin-macos-native-theme#79]
How to make the Theme follow the fonts in `userstyle.css` ?

My CSS :

```
/* For styling the rendered Markdown */
body {
    font-family: "Roboto Mono";
    /* sets body font */
    font-size: 14px;
    /* sets body text font size in pixels */
    color: #000;
    /* sets body text font colour */
} 
```

Before I use this theme, I was able to see my Font in both MD and Richtext editors as roboto mono. Now, This doesn't apply in both  of them.

**Comment by andrejilderda** [comment]
Hi @IkelAtomig , you can overwrite the font-families for both the `userstyle.css` & `userchrome.css` like so:
```css
:root:root {
  --s-font-family-system: "Roboto Mono";
}
```

Sorry for the late reply!

**Comment by andrejilderda** [comment]
I agree @lifepillar , that it should respect the user's setting, but this theme consists of many hacks to override the default Joplin styles. Many things have changed in CSS since first releasing this, so maybe it is now possible to solve in an elegant way. Feel free to open a PR if you're up for a challenge!
