### ISSUE TITLE
How to edit hyperlink color?

### ISSUE THREAD

**Issue by hynow** [andrejilderda/joplin-macos-native-theme#85]
Hello, is it possible to edit hyperlink colors?  I believe it is technically possible, as I have seen this effect in other themes.

Is there a hex code I can change by editing a .jpl file with a text editor?

Or would you ever consider making the accent color also apply to hyperlinks?

Related: is it possible to also change the blue color of the checkboxes that are present in Joplin settings?  For example, the "hide sync status" box under  the accent color selection.  I am primarily wondering because the same checkboxes seem to be used in another plugin called "Agenda", which creates a todo sidebar.

Thanks!!

**Comment by andrejilderda** [comment]
Hi @hynow , you can change the hyperlink color by adding the following to your `userstyle.css`:

```css
:root:root {
  --g-linkColor: red;
}
```

To find the path to your go to Joplin settings › Appearance › Show Advanced Settings › Custom stylesheet for rendered Markdown.

For the checkbox, there are a lot of different implementations of UI elements throughout Joplin's interface. That's why the same element - in this case a checkbox - may not automatically get the theme style applied unfortunately. I don't want to also take on styling all elements appended by plugins tbh. If you are eager to style it yourself you can take reuse parts of this [Sass mixin](https://github.com/andrejilderda/joplin-macos-native-theme/blob/09ed6f4d9312675432db7d7eb96001eb9861b257/src/scss/components/_components.mixins.checkbox.scss) and apply it to your element yourself by adding it to userchrome.css.

**Comment by hynow** [comment]
Thanks a lot for your help!!  The hyperlink change works great and looks awesome.

I couldn't figure out the checkboxes though.  I copied all the lines from your link to userchrome.css and changed all four instances of "var(text here)" to "red" but nothing happened.  I have no idea what I'm doing though!

**Comment by andrejilderda** [comment]
Good to hear! 

I've installed the Agenda plugin, but I think it's actually impossible to style anything inside the sidebar using the `userchrome.css` since the styles are not added to the iframe (I believe).

**Comment by hynow** [comment]
Ah well, that's okay.  I may end up just using the "notes overview" plugin instead.  I have one table for todo's and another one that lists notes/todo's that have checkboxes inside of them.  It does the trick, just without being able to check the todo boxes without navigating via hyperlink (ctrl + click), which is not a big deal.
